import { CurrencyCode } from '../context/CurrencyContext';
import { Locale } from '../context/I18nContext';

// Mapeamento de país para moeda (usa apenas moedas suportadas, USD como fallback)
export const COUNTRY_CURRENCY_MAP: Record<string, CurrencyCode> = {
  // Américas
  'BR': 'BRL', 'US': 'USD', 'CA': 'CAD', 'MX': 'MXN', 'AR': 'ARS', 'CL': 'CLP', 'CO': 'COP', 'UY': 'UYU',
  'PE': 'USD', 'BO': 'USD', 'PY': 'USD', 'VE': 'USD', 'EC': 'USD', 'GY': 'USD', 'SR': 'USD',
  'CR': 'USD', 'PA': 'USD', 'NI': 'USD', 'HN': 'USD', 'GT': 'USD', 'BZ': 'USD', 'SV': 'USD',
  'JM': 'USD', 'HT': 'USD', 'CU': 'USD', 'DO': 'USD', 'PR': 'USD', 'TT': 'USD', 'BB': 'USD',
  'BS': 'USD', 'AG': 'USD', 'DM': 'USD', 'GD': 'USD', 'KN': 'USD', 'LC': 'USD', 'VC': 'USD',
  
  // Europa
  'GB': 'GBP', 'CH': 'CHF', 'DE': 'EUR', 'FR': 'EUR', 'ES': 'EUR', 'IT': 'EUR', 'SE': 'SEK',
  'NO': 'NOK', 'DK': 'DKK', 'PL': 'PLN', 'RU': 'RUB', 'TR': 'TRY', 'AT': 'EUR', 'BE': 'EUR',
  'FI': 'EUR', 'GR': 'EUR', 'IE': 'EUR', 'LU': 'EUR', 'NL': 'EUR', 'PT': 'EUR', 'IS': 'USD',
  'CZ': 'USD', 'HU': 'USD', 'RO': 'USD', 'BG': 'USD', 'HR': 'USD', 'RS': 'USD', 'BA': 'USD',
  'MK': 'USD', 'AL': 'USD', 'ME': 'EUR', 'XK': 'EUR', 'SI': 'EUR', 'SK': 'EUR', 'EE': 'EUR',
  'LV': 'EUR', 'LT': 'EUR', 'BY': 'USD', 'UA': 'USD', 'MD': 'USD', 'GE': 'USD', 'AM': 'USD',
  'AZ': 'USD', 'CY': 'EUR', 'MT': 'EUR', 'AD': 'EUR', 'LI': 'CHF', 'MC': 'EUR', 'SM': 'EUR', 'VA': 'EUR',
  
  // Ásia
  'CN': 'CNY', 'JP': 'JPY', 'IN': 'INR', 'ID': 'IDR', 'PK': 'PKR', 'KR': 'KRW', 'SG': 'SGD',
  'TH': 'THB', 'VN': 'VND', 'PH': 'PHP', 'MY': 'MYR', 'BD': 'USD', 'MM': 'USD', 'KH': 'USD',
  'LA': 'USD', 'BN': 'USD', 'TL': 'USD', 'MN': 'USD', 'KZ': 'USD', 'UZ': 'USD', 'TJ': 'USD',
  'TM': 'USD', 'KG': 'USD', 'AF': 'USD', 'IR': 'USD', 'IQ': 'USD', 'SA': 'USD', 'AE': 'USD',
  'OM': 'USD', 'YE': 'USD', 'KW': 'USD', 'QA': 'USD', 'BH': 'USD', 'JO': 'USD', 'LB': 'USD',
  'SY': 'USD', 'IL': 'USD', 'PS': 'USD', 'LK': 'USD', 'MV': 'USD', 'NP': 'USD', 'BT': 'USD',
  'TW': 'USD', 'HK': 'HKD', 'MO': 'USD', 'KP': 'USD',
  
  // África
  'ZA': 'ZAR', 'NG': 'USD', 'KE': 'USD', 'ET': 'USD', 'EG': 'USD', 'MA': 'USD', 'DZ': 'USD',
  'TN': 'USD', 'LY': 'USD', 'SD': 'USD', 'SS': 'USD', 'UG': 'USD', 'TZ': 'USD', 'RW': 'USD',
  'BI': 'USD', 'DJ': 'USD', 'ER': 'USD', 'SO': 'USD', 'GH': 'USD', 'SN': 'USD', 'ML': 'USD',
  'BF': 'USD', 'NE': 'USD', 'TD': 'USD', 'CM': 'USD', 'CF': 'USD', 'GA': 'USD', 'GQ': 'USD',
  'CG': 'USD', 'CD': 'USD', 'AO': 'USD', 'ZM': 'USD', 'MW': 'USD', 'MZ': 'USD', 'ZW': 'USD',
  'BW': 'USD', 'NA': 'USD', 'SZ': 'USD', 'LS': 'USD', 'MG': 'USD', 'MU': 'USD', 'SC': 'USD',
  'KM': 'USD', 'CV': 'USD', 'GW': 'USD', 'GN': 'USD', 'SL': 'USD', 'LR': 'USD', 'CI': 'USD',
  'TG': 'USD', 'BJ': 'USD', 'MR': 'USD', 'GM': 'USD', 'ST': 'USD',
  
  // Oceania
  'AU': 'AUD', 'NZ': 'NZD', 'PG': 'USD', 'FJ': 'USD', 'SB': 'USD', 'VU': 'USD', 'NC': 'USD',
  'PF': 'USD', 'WS': 'USD', 'TO': 'USD', 'TV': 'AUD', 'KI': 'AUD', 'NR': 'AUD', 'PW': 'USD',
  'FM': 'USD', 'MH': 'USD', 'AS': 'USD', 'GU': 'USD', 'MP': 'USD',
};

// Lista completa de todos os países do mundo (195 países reconhecidos pela ONU)
export const COUNTRIES = [
  // África (54 países)
  { code: 'ZA', name: 'África do Sul', currency: 'ZAR' },
  { code: 'AO', name: 'Angola', currency: 'USD' },
  { code: 'DZ', name: 'Argélia', currency: 'USD' },
  { code: 'BJ', name: 'Benin', currency: 'USD' },
  { code: 'BW', name: 'Botsuana', currency: 'USD' },
  { code: 'BF', name: 'Burquina Fasso', currency: 'USD' },
  { code: 'BI', name: 'Burundi', currency: 'USD' },
  { code: 'CV', name: 'Cabo Verde', currency: 'USD' },
  { code: 'CM', name: 'Camarões', currency: 'USD' },
  { code: 'TD', name: 'Chade', currency: 'USD' },
  { code: 'KM', name: 'Comores', currency: 'USD' },
  { code: 'CG', name: 'Congo', currency: 'USD' },
  { code: 'CD', name: 'República Democrática do Congo', currency: 'USD' },
  { code: 'CI', name: 'Costa do Marfim', currency: 'USD' },
  { code: 'DJ', name: 'Djibuti', currency: 'USD' },
  { code: 'EG', name: 'Egito', currency: 'USD' },
  { code: 'ER', name: 'Eritreia', currency: 'USD' },
  { code: 'SZ', name: 'Eswatini', currency: 'USD' },
  { code: 'ET', name: 'Etiópia', currency: 'USD' },
  { code: 'GA', name: 'Gabão', currency: 'USD' },
  { code: 'GM', name: 'Gâmbia', currency: 'USD' },
  { code: 'GH', name: 'Gana', currency: 'USD' },
  { code: 'GN', name: 'Guiné', currency: 'USD' },
  { code: 'GW', name: 'Guiné-Bissau', currency: 'USD' },
  { code: 'GQ', name: 'Guiné Equatorial', currency: 'USD' },
  { code: 'LS', name: 'Lesoto', currency: 'USD' },
  { code: 'LR', name: 'Libéria', currency: 'USD' },
  { code: 'LY', name: 'Líbia', currency: 'USD' },
  { code: 'MG', name: 'Madagáscar', currency: 'USD' },
  { code: 'MW', name: 'Maláui', currency: 'USD' },
  { code: 'ML', name: 'Mali', currency: 'USD' },
  { code: 'MA', name: 'Marrocos', currency: 'USD' },
  { code: 'MU', name: 'Maurícia', currency: 'USD' },
  { code: 'MR', name: 'Mauritânia', currency: 'USD' },
  { code: 'MZ', name: 'Moçambique', currency: 'USD' },
  { code: 'NA', name: 'Namíbia', currency: 'USD' },
  { code: 'NE', name: 'Níger', currency: 'USD' },
  { code: 'NG', name: 'Nigéria', currency: 'USD' },
  { code: 'KE', name: 'Quênia', currency: 'USD' },
  { code: 'CF', name: 'República Centro-Africana', currency: 'USD' },
  { code: 'RW', name: 'Ruanda', currency: 'USD' },
  { code: 'ST', name: 'São Tomé e Príncipe', currency: 'USD' },
  { code: 'SN', name: 'Senegal', currency: 'USD' },
  { code: 'SL', name: 'Serra Leoa', currency: 'USD' },
  { code: 'SC', name: 'Seychelles', currency: 'USD' },
  { code: 'SO', name: 'Somália', currency: 'USD' },
  { code: 'SD', name: 'Sudão', currency: 'USD' },
  { code: 'SS', name: 'Sudão do Sul', currency: 'USD' },
  { code: 'TZ', name: 'Tanzânia', currency: 'USD' },
  { code: 'TG', name: 'Togo', currency: 'USD' },
  { code: 'TN', name: 'Tunísia', currency: 'USD' },
  { code: 'UG', name: 'Uganda', currency: 'USD' },
  { code: 'ZM', name: 'Zâmbia', currency: 'USD' },
  { code: 'ZW', name: 'Zimbábue', currency: 'USD' },
  
  // América (35 países)
  { code: 'AG', name: 'Antígua e Barbuda', currency: 'USD' },
  { code: 'AR', name: 'Argentina', currency: 'ARS' },
  { code: 'BS', name: 'Bahamas', currency: 'USD' },
  { code: 'BB', name: 'Barbados', currency: 'USD' },
  { code: 'BZ', name: 'Belize', currency: 'USD' },
  { code: 'BO', name: 'Bolívia', currency: 'USD' },
  { code: 'BR', name: 'Brasil', currency: 'BRL' },
  { code: 'CA', name: 'Canadá', currency: 'CAD' },
  { code: 'CL', name: 'Chile', currency: 'CLP' },
  { code: 'CO', name: 'Colômbia', currency: 'COP' },
  { code: 'CR', name: 'Costa Rica', currency: 'USD' },
  { code: 'CU', name: 'Cuba', currency: 'USD' },
  { code: 'DM', name: 'Dominica', currency: 'USD' },
  { code: 'DO', name: 'República Dominicana', currency: 'USD' },
  { code: 'EC', name: 'Equador', currency: 'USD' },
  { code: 'SV', name: 'El Salvador', currency: 'USD' },
  { code: 'GD', name: 'Granada', currency: 'USD' },
  { code: 'GT', name: 'Guatemala', currency: 'USD' },
  { code: 'GY', name: 'Guiana', currency: 'USD' },
  { code: 'HT', name: 'Haiti', currency: 'USD' },
  { code: 'HN', name: 'Honduras', currency: 'USD' },
  { code: 'JM', name: 'Jamaica', currency: 'USD' },
  { code: 'MX', name: 'México', currency: 'MXN' },
  { code: 'NI', name: 'Nicarágua', currency: 'USD' },
  { code: 'PA', name: 'Panamá', currency: 'USD' },
  { code: 'PY', name: 'Paraguai', currency: 'USD' },
  { code: 'PE', name: 'Peru', currency: 'USD' },
  { code: 'KN', name: 'São Cristóvão e Neves', currency: 'USD' },
  { code: 'LC', name: 'Santa Lúcia', currency: 'USD' },
  { code: 'VC', name: 'São Vicente e Granadinas', currency: 'USD' },
  { code: 'SR', name: 'Suriname', currency: 'USD' },
  { code: 'TT', name: 'Trinidad e Tobago', currency: 'USD' },
  { code: 'US', name: 'Estados Unidos', currency: 'USD' },
  { code: 'UY', name: 'Uruguai', currency: 'UYU' },
  { code: 'VE', name: 'Venezuela', currency: 'USD' },
  
  // Ásia (48 países)
  { code: 'AF', name: 'Afeganistão', currency: 'USD' },
  { code: 'SA', name: 'Arábia Saudita', currency: 'USD' },
  { code: 'AM', name: 'Armênia', currency: 'USD' },
  { code: 'AZ', name: 'Azerbaijão', currency: 'USD' },
  { code: 'BH', name: 'Bahrein', currency: 'USD' },
  { code: 'BD', name: 'Bangladesh', currency: 'USD' },
  { code: 'BN', name: 'Brunei', currency: 'USD' },
  { code: 'BT', name: 'Butão', currency: 'USD' },
  { code: 'KH', name: 'Camboja', currency: 'USD' },
  { code: 'KZ', name: 'Cazaquistão', currency: 'USD' },
  { code: 'CN', name: 'China', currency: 'CNY' },
  { code: 'CY', name: 'Chipre', currency: 'EUR' },
  { code: 'KP', name: 'Coreia do Norte', currency: 'USD' },
  { code: 'KR', name: 'Coreia do Sul', currency: 'KRW' },
  { code: 'AE', name: 'Emirados Árabes Unidos', currency: 'USD' },
  { code: 'PH', name: 'Filipinas', currency: 'PHP' },
  { code: 'GE', name: 'Geórgia', currency: 'USD' },
  { code: 'IN', name: 'Índia', currency: 'INR' },
  { code: 'ID', name: 'Indonésia', currency: 'IDR' },
  { code: 'IQ', name: 'Iraque', currency: 'USD' },
  { code: 'IR', name: 'Irã', currency: 'USD' },
  { code: 'IL', name: 'Israel', currency: 'USD' },
  { code: 'YE', name: 'Iêmen', currency: 'USD' },
  { code: 'JO', name: 'Jordânia', currency: 'USD' },
  { code: 'JP', name: 'Japão', currency: 'JPY' },
  { code: 'KW', name: 'Kuwait', currency: 'USD' },
  { code: 'LA', name: 'Laos', currency: 'USD' },
  { code: 'LB', name: 'Líbano', currency: 'USD' },
  { code: 'MY', name: 'Malásia', currency: 'MYR' },
  { code: 'MV', name: 'Maldivas', currency: 'USD' },
  { code: 'MM', name: 'Mianmar', currency: 'USD' },
  { code: 'MN', name: 'Mongólia', currency: 'USD' },
  { code: 'NP', name: 'Nepal', currency: 'USD' },
  { code: 'OM', name: 'Omã', currency: 'USD' },
  { code: 'PK', name: 'Paquistão', currency: 'PKR' },
  { code: 'QA', name: 'Qatar', currency: 'USD' },
  { code: 'KG', name: 'Quirguistão', currency: 'USD' },
  { code: 'RU', name: 'Rússia', currency: 'RUB' },
  { code: 'SG', name: 'Singapura', currency: 'SGD' },
  { code: 'SY', name: 'Síria', currency: 'USD' },
  { code: 'LK', name: 'Sri Lanka', currency: 'USD' },
  { code: 'TJ', name: 'Tajiquistão', currency: 'USD' },
  { code: 'TH', name: 'Tailândia', currency: 'THB' },
  { code: 'TL', name: 'Timor-Leste', currency: 'USD' },
  { code: 'TM', name: 'Turcomenistão', currency: 'USD' },
  { code: 'TR', name: 'Turquia', currency: 'TRY' },
  { code: 'UZ', name: 'Uzbequistão', currency: 'USD' },
  { code: 'VN', name: 'Vietnã', currency: 'VND' },
  { code: 'PS', name: 'Palestina', currency: 'USD' },
  { code: 'TW', name: 'Taiwan', currency: 'USD' },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD' },
  { code: 'MO', name: 'Macau', currency: 'USD' },
  
  // Europa (44 países)
  { code: 'AL', name: 'Albânia', currency: 'USD' },
  { code: 'DE', name: 'Alemanha', currency: 'EUR' },
  { code: 'AD', name: 'Andorra', currency: 'EUR' },
  { code: 'AT', name: 'Áustria', currency: 'EUR' },
  { code: 'BE', name: 'Bélgica', currency: 'EUR' },
  { code: 'BY', name: 'Bielorrússia', currency: 'USD' },
  { code: 'BA', name: 'Bósnia e Herzegovina', currency: 'USD' },
  { code: 'BG', name: 'Bulgária', currency: 'USD' },
  { code: 'HR', name: 'Croácia', currency: 'USD' },
  { code: 'DK', name: 'Dinamarca', currency: 'DKK' },
  { code: 'SK', name: 'Eslováquia', currency: 'EUR' },
  { code: 'SI', name: 'Eslovênia', currency: 'EUR' },
  { code: 'ES', name: 'Espanha', currency: 'EUR' },
  { code: 'EE', name: 'Estônia', currency: 'EUR' },
  { code: 'FI', name: 'Finlândia', currency: 'EUR' },
  { code: 'FR', name: 'França', currency: 'EUR' },
  { code: 'GR', name: 'Grécia', currency: 'EUR' },
  { code: 'HU', name: 'Hungria', currency: 'USD' },
  { code: 'IE', name: 'Irlanda', currency: 'EUR' },
  { code: 'IS', name: 'Islândia', currency: 'USD' },
  { code: 'IT', name: 'Itália', currency: 'EUR' },
  { code: 'LV', name: 'Letônia', currency: 'EUR' },
  { code: 'LI', name: 'Liechtenstein', currency: 'CHF' },
  { code: 'LT', name: 'Lituânia', currency: 'EUR' },
  { code: 'LU', name: 'Luxemburgo', currency: 'EUR' },
  { code: 'MT', name: 'Malta', currency: 'EUR' },
  { code: 'MD', name: 'Moldávia', currency: 'USD' },
  { code: 'MC', name: 'Mônaco', currency: 'EUR' },
  { code: 'ME', name: 'Montenegro', currency: 'EUR' },
  { code: 'NL', name: 'Países Baixos', currency: 'EUR' },
  { code: 'MK', name: 'Macedônia do Norte', currency: 'USD' },
  { code: 'NO', name: 'Noruega', currency: 'NOK' },
  { code: 'PL', name: 'Polônia', currency: 'PLN' },
  { code: 'PT', name: 'Portugal', currency: 'EUR' },
  { code: 'GB', name: 'Reino Unido', currency: 'GBP' },
  { code: 'RO', name: 'Romênia', currency: 'USD' },
  { code: 'SM', name: 'San Marino', currency: 'EUR' },
  { code: 'RS', name: 'Sérvia', currency: 'USD' },
  { code: 'SE', name: 'Suécia', currency: 'SEK' },
  { code: 'CH', name: 'Suíça', currency: 'CHF' },
  { code: 'UA', name: 'Ucrânia', currency: 'USD' },
  { code: 'VA', name: 'Vaticano', currency: 'EUR' },
  { code: 'XK', name: 'Kosovo', currency: 'EUR' },
  
  // Oceania (14 países)
  { code: 'AU', name: 'Austrália', currency: 'AUD' },
  { code: 'FJ', name: 'Fiji', currency: 'USD' },
  { code: 'KI', name: 'Kiribati', currency: 'AUD' },
  { code: 'MH', name: 'Ilhas Marshall', currency: 'USD' },
  { code: 'FM', name: 'Micronésia', currency: 'USD' },
  { code: 'NR', name: 'Nauru', currency: 'AUD' },
  { code: 'NZ', name: 'Nova Zelândia', currency: 'NZD' },
  { code: 'PW', name: 'Palau', currency: 'USD' },
  { code: 'PG', name: 'Papua Nova Guiné', currency: 'USD' },
  { code: 'WS', name: 'Samoa', currency: 'USD' },
  { code: 'SB', name: 'Ilhas Salomão', currency: 'USD' },
  { code: 'TO', name: 'Tonga', currency: 'USD' },
  { code: 'TV', name: 'Tuvalu', currency: 'AUD' },
  { code: 'VU', name: 'Vanuatu', currency: 'USD' },
];

// Idiomas disponíveis
export const LANGUAGES: { code: Locale; name: string; nativeName: string }[] = [
  { code: 'pt-BR', name: 'Português (Brasil)', nativeName: 'Português' },
  { code: 'en-US', name: 'English (US)', nativeName: 'English' },
  { code: 'es-ES', name: 'Español (España)', nativeName: 'Español' },
  { code: 'ja-JP', name: '日本語 (Japonês)', nativeName: '日本語' },
  { code: 'ru-RU', name: 'Русский (Russo)', nativeName: 'Русский' },
  { code: 'zh-CN', name: '中文 (Mandarim)', nativeName: '中文' },
  { code: 'fr-FR', name: 'Français (Francês)', nativeName: 'Français' },
  { code: 'ar-SA', name: 'العربية (Árabe)', nativeName: 'العربية' },
];

